/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `client`;

CREATE TABLE `client` (
  `client_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `client_type` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `contact_person` TEXT NOT NULL,
  `phone` TEXT NOT NULL,
  `email` TEXT NOT NULL)
 ENGINE=InnoDB;

