// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef CLIENT_ODB_HXX
#define CLIENT_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "client.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Client
  //
  template <>
  struct class_traits< ::Client >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Client >
  {
    public:
    typedef ::Client object_type;
    typedef ::std::shared_ptr< ::Client > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Client
  //
  template <typename A>
  struct query_columns< ::Client, id_mysql, A >
  {
    // client_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    client_id_type_;

    static const client_id_type_ client_id;

    // client_type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    client_type_type_;

    static const client_type_type_ client_type;

    // name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    name_type_;

    static const name_type_ name;

    // contact_person
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    contact_person_type_;

    static const contact_person_type_ contact_person;

    // phone
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    phone_type_;

    static const phone_type_ phone;

    // email
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    email_type_;

    static const email_type_ email;
  };

  template <typename A>
  const typename query_columns< ::Client, id_mysql, A >::client_id_type_
  query_columns< ::Client, id_mysql, A >::
  client_id (A::table_name, "`client_id`", 0);

  template <typename A>
  const typename query_columns< ::Client, id_mysql, A >::client_type_type_
  query_columns< ::Client, id_mysql, A >::
  client_type (A::table_name, "`client_type`", 0);

  template <typename A>
  const typename query_columns< ::Client, id_mysql, A >::name_type_
  query_columns< ::Client, id_mysql, A >::
  name (A::table_name, "`name`", 0);

  template <typename A>
  const typename query_columns< ::Client, id_mysql, A >::contact_person_type_
  query_columns< ::Client, id_mysql, A >::
  contact_person (A::table_name, "`contact_person`", 0);

  template <typename A>
  const typename query_columns< ::Client, id_mysql, A >::phone_type_
  query_columns< ::Client, id_mysql, A >::
  phone (A::table_name, "`phone`", 0);

  template <typename A>
  const typename query_columns< ::Client, id_mysql, A >::email_type_
  query_columns< ::Client, id_mysql, A >::
  email (A::table_name, "`email`", 0);

  template <typename A>
  struct pointer_query_columns< ::Client, id_mysql, A >:
    query_columns< ::Client, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Client, id_mysql >:
    public access::object_traits< ::Client >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // client_id
      //
      unsigned long long client_id_value;
      my_bool client_id_null;

      // client_type
      //
      details::buffer client_type_value;
      unsigned long client_type_size;
      my_bool client_type_null;

      // name_
      //
      details::buffer name_value;
      unsigned long name_size;
      my_bool name_null;

      // contact_person
      //
      details::buffer contact_person_value;
      unsigned long contact_person_size;
      my_bool contact_person_null;

      // phone
      //
      details::buffer phone_value;
      unsigned long phone_size;
      my_bool phone_null;

      // email
      //
      details::buffer email_value;
      unsigned long email_size;
      my_bool email_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Client, id_common >:
    public access::object_traits_impl< ::Client, id_mysql >
  {
  };

  // Client
  //
}

#include "client-odb.ixx"

#include <odb/post.hxx>

#endif // CLIENT_ODB_HXX
