/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `driver`;

CREATE TABLE `driver` (
  `driver_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `first_name` TEXT NOT NULL,
  `last_name` TEXT NOT NULL,
  `license_number` TEXT NOT NULL,
  `license_category` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phone` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `license_number_i`
  ON `driver` (`license_number`);

