// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DRIVER_ODB_HXX
#define DRIVER_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "driver.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Driver
  //
  template <>
  struct class_traits< ::Driver >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Driver >
  {
    public:
    typedef ::Driver object_type;
    typedef ::std::shared_ptr< ::Driver > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Driver
  //
  template <typename A>
  struct query_columns< ::Driver, id_mysql, A >
  {
    // driver_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    driver_id_type_;

    static const driver_id_type_ driver_id;

    // first_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    first_name_type_;

    static const first_name_type_ first_name;

    // last_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    last_name_type_;

    static const last_name_type_ last_name;

    // license_number
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    license_number_type_;

    static const license_number_type_ license_number;

    // license_category
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    license_category_type_;

    static const license_category_type_ license_category;

    // email
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    email_type_;

    static const email_type_ email;

    // phone
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    phone_type_;

    static const phone_type_ phone;
  };

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::driver_id_type_
  query_columns< ::Driver, id_mysql, A >::
  driver_id (A::table_name, "`driver_id`", 0);

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::first_name_type_
  query_columns< ::Driver, id_mysql, A >::
  first_name (A::table_name, "`first_name`", 0);

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::last_name_type_
  query_columns< ::Driver, id_mysql, A >::
  last_name (A::table_name, "`last_name`", 0);

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::license_number_type_
  query_columns< ::Driver, id_mysql, A >::
  license_number (A::table_name, "`license_number`", 0);

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::license_category_type_
  query_columns< ::Driver, id_mysql, A >::
  license_category (A::table_name, "`license_category`", 0);

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::email_type_
  query_columns< ::Driver, id_mysql, A >::
  email (A::table_name, "`email`", 0);

  template <typename A>
  const typename query_columns< ::Driver, id_mysql, A >::phone_type_
  query_columns< ::Driver, id_mysql, A >::
  phone (A::table_name, "`phone`", 0);

  template <typename A>
  struct pointer_query_columns< ::Driver, id_mysql, A >:
    query_columns< ::Driver, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Driver, id_mysql >:
    public access::object_traits< ::Driver >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // driver_id_
      //
      unsigned long long driver_id_value;
      my_bool driver_id_null;

      // first_name_
      //
      details::buffer first_name_value;
      unsigned long first_name_size;
      my_bool first_name_null;

      // last_name_
      //
      details::buffer last_name_value;
      unsigned long last_name_size;
      my_bool last_name_null;

      // license_number_
      //
      details::buffer license_number_value;
      unsigned long license_number_size;
      my_bool license_number_null;

      // license_category_
      //
      details::buffer license_category_value;
      unsigned long license_category_size;
      my_bool license_category_null;

      // email_
      //
      details::buffer email_value;
      unsigned long email_size;
      my_bool email_null;

      // phone_
      //
      details::buffer phone_value;
      unsigned long phone_size;
      my_bool phone_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Driver, id_common >:
    public access::object_traits_impl< ::Driver, id_mysql >
  {
  };

  // Driver
  //
}

#include "driver-odb.ixx"

#include <odb/post.hxx>

#endif // DRIVER_ODB_HXX
