// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "order-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // Order
  //

  struct access::object_traits_impl< ::Order, id_mysql >::extra_statement_cache_type
  {
    mysql::container_statements_impl< triplogs_traits > triplogs_;
    mysql::container_statements_impl< tripdetails_traits > tripdetails_;

    extra_statement_cache_type (
      mysql::connection& c,
      image_type&,
      id_image_type&,
      mysql::binding& id,
      mysql::binding&)
    : triplogs_ (c, id),
      tripdetails_ (c, id)
    {
    }
  };

  // triplogs_
  //

  const char access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  select_statement[] =
  "SELECT "
  "`triplog`.`login_id` "
  "FROM `triplog` "
  "WHERE `triplog`.`order_id`=?";

  const char access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  insert_statement[] =
  "";

  const char access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  delete_statement[] =
  "";

  void access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // value
    //
    t[0UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  init (value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      typedef object_traits< ::TripLog > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          ptr_id,
          i.value_value,
          i.value_null);

        v = ptr_traits::pointer_type (
          *static_cast<mysql::database*> (db), ptr_id);
      }
    }
  }

  void access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  insert (index_type, const value_type&, void*)
  {
  }

  bool access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  select (index_type&, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (v, di, &sts.connection ().database ());

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  delete_ (void*)
  {
  }

  void access::object_traits_impl< ::Order, id_mysql >::triplogs_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = false;
    container_traits_type::load (c, more, fs);
  }

  // tripdetails_
  //

  const char access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  select_statement[] =
  "SELECT "
  "`tripdetails`.`trip_id` "
  "FROM `tripdetails` "
  "WHERE `tripdetails`.`order_id`=?";

  const char access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  insert_statement[] =
  "";

  const char access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  delete_statement[] =
  "";

  void access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // value
    //
    t[0UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  init (value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      typedef object_traits< ::TripDetails > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          ptr_id,
          i.value_value,
          i.value_null);

        v = ptr_traits::pointer_type (
          *static_cast<mysql::database*> (db), ptr_id);
      }
    }
  }

  void access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  insert (index_type, const value_type&, void*)
  {
  }

  bool access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  select (index_type&, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (v, di, &sts.connection ().database ());

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  delete_ (void*)
  {
  }

  void access::object_traits_impl< ::Order, id_mysql >::tripdetails_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = false;
    container_traits_type::load (c, more, fs);
  }

  access::object_traits_impl< ::Order, id_mysql >::id_type
  access::object_traits_impl< ::Order, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::Order, id_mysql >::id_type
  access::object_traits_impl< ::Order, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.order_id_value,
        i.order_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Order, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // order_id_
    //
    t[0UL] = 0;

    // client_id_
    //
    t[1UL] = 0;

    // driver_id_
    //
    t[2UL] = 0;

    // vehicle_id_
    //
    t[3UL] = 0;

    // route_from_
    //
    if (t[4UL])
    {
      i.route_from_value.capacity (i.route_from_size);
      grew = true;
    }

    // route_to_
    //
    if (t[5UL])
    {
      i.route_to_value.capacity (i.route_to_size);
      grew = true;
    }

    // cargo_details_
    //
    if (t[6UL])
    {
      i.cargo_details_value.capacity (i.cargo_details_size);
      grew = true;
    }

    // order_status_
    //
    if (t[7UL])
    {
      i.order_status_value.capacity (i.order_status_size);
      grew = true;
    }

    // planned_departure_time_
    //
    if (t[8UL])
    {
      i.planned_departure_time_value.capacity (i.planned_departure_time_size);
      grew = true;
    }

    // planned_arrival_time_
    //
    if (t[9UL])
    {
      i.planned_arrival_time_value.capacity (i.planned_arrival_time_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // order_id_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.order_id_value;
      b[n].is_null = &i.order_id_null;
      n++;
    }

    // client_id_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.client_id_value;
    b[n].is_null = &i.client_id_null;
    n++;

    // driver_id_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.driver_id_value;
    b[n].is_null = &i.driver_id_null;
    n++;

    // vehicle_id_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.vehicle_id_value;
    b[n].is_null = &i.vehicle_id_null;
    n++;

    // route_from_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.route_from_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.route_from_value.capacity ());
    b[n].length = &i.route_from_size;
    b[n].is_null = &i.route_from_null;
    n++;

    // route_to_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.route_to_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.route_to_value.capacity ());
    b[n].length = &i.route_to_size;
    b[n].is_null = &i.route_to_null;
    n++;

    // cargo_details_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.cargo_details_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.cargo_details_value.capacity ());
    b[n].length = &i.cargo_details_size;
    b[n].is_null = &i.cargo_details_null;
    n++;

    // order_status_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.order_status_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.order_status_value.capacity ());
    b[n].length = &i.order_status_size;
    b[n].is_null = &i.order_status_null;
    n++;

    // planned_departure_time_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.planned_departure_time_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.planned_departure_time_value.capacity ());
    b[n].length = &i.planned_departure_time_size;
    b[n].is_null = &i.planned_departure_time_null;
    n++;

    // planned_arrival_time_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.planned_arrival_time_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.planned_arrival_time_value.capacity ());
    b[n].length = &i.planned_arrival_time_size;
    b[n].is_null = &i.planned_arrival_time_null;
    n++;
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Order, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // order_id_
    //
    if (sk == statement_insert)
    {
      long unsigned int const& v =
        o.order_id_;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.order_id_value, is_null, v);
      i.order_id_null = is_null;
    }

    // client_id_
    //
    {
      long unsigned int const& v =
        o.client_id_;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.client_id_value, is_null, v);
      i.client_id_null = is_null;
    }

    // driver_id_
    //
    {
      long unsigned int const& v =
        o.driver_id_;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.driver_id_value, is_null, v);
      i.driver_id_null = is_null;
    }

    // vehicle_id_
    //
    {
      long unsigned int const& v =
        o.vehicle_id_;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.vehicle_id_value, is_null, v);
      i.vehicle_id_null = is_null;
    }

    // route_from_
    //
    {
      ::std::string const& v =
        o.route_from_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.route_from_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.route_from_value,
        size,
        is_null,
        v);
      i.route_from_null = is_null;
      i.route_from_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.route_from_value.capacity ());
    }

    // route_to_
    //
    {
      ::std::string const& v =
        o.route_to_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.route_to_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.route_to_value,
        size,
        is_null,
        v);
      i.route_to_null = is_null;
      i.route_to_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.route_to_value.capacity ());
    }

    // cargo_details_
    //
    {
      ::std::string const& v =
        o.cargo_details_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.cargo_details_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.cargo_details_value,
        size,
        is_null,
        v);
      i.cargo_details_null = is_null;
      i.cargo_details_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.cargo_details_value.capacity ());
    }

    // order_status_
    //
    {
      ::std::string const& v =
        o.order_status_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.order_status_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.order_status_value,
        size,
        is_null,
        v);
      i.order_status_null = is_null;
      i.order_status_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.order_status_value.capacity ());
    }

    // planned_departure_time_
    //
    {
      ::std::string const& v =
        o.planned_departure_time_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.planned_departure_time_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.planned_departure_time_value,
        size,
        is_null,
        v);
      i.planned_departure_time_null = is_null;
      i.planned_departure_time_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.planned_departure_time_value.capacity ());
    }

    // planned_arrival_time_
    //
    {
      ::std::string const& v =
        o.planned_arrival_time_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.planned_arrival_time_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.planned_arrival_time_value,
        size,
        is_null,
        v);
      i.planned_arrival_time_null = is_null;
      i.planned_arrival_time_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.planned_arrival_time_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // order_id_
    //
    {
      long unsigned int& v =
        o.order_id_;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.order_id_value,
        i.order_id_null);
    }

    // client_id_
    //
    {
      long unsigned int& v =
        o.client_id_;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.client_id_value,
        i.client_id_null);
    }

    // driver_id_
    //
    {
      long unsigned int& v =
        o.driver_id_;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.driver_id_value,
        i.driver_id_null);
    }

    // vehicle_id_
    //
    {
      long unsigned int& v =
        o.vehicle_id_;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.vehicle_id_value,
        i.vehicle_id_null);
    }

    // route_from_
    //
    {
      ::std::string& v =
        o.route_from_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.route_from_value,
        i.route_from_size,
        i.route_from_null);
    }

    // route_to_
    //
    {
      ::std::string& v =
        o.route_to_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.route_to_value,
        i.route_to_size,
        i.route_to_null);
    }

    // cargo_details_
    //
    {
      ::std::string& v =
        o.cargo_details_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.cargo_details_value,
        i.cargo_details_size,
        i.cargo_details_null);
    }

    // order_status_
    //
    {
      ::std::string& v =
        o.order_status_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.order_status_value,
        i.order_status_size,
        i.order_status_null);
    }

    // planned_departure_time_
    //
    {
      ::std::string& v =
        o.planned_departure_time_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.planned_departure_time_value,
        i.planned_departure_time_size,
        i.planned_departure_time_null);
    }

    // planned_arrival_time_
    //
    {
      ::std::string& v =
        o.planned_arrival_time_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.planned_arrival_time_value,
        i.planned_arrival_time_size,
        i.planned_arrival_time_null);
    }
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Order, id_mysql >::persist_statement[] =
  "INSERT INTO `order` "
  "(`order_id`, "
  "`client_id`, "
  "`driver_id`, "
  "`vehicle_id`, "
  "`route_from`, "
  "`route_to`, "
  "`cargo_details`, "
  "`order_status`, "
  "`planned_departure_time`, "
  "`planned_arrival_time`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Order, id_mysql >::find_statement[] =
  "SELECT "
  "`order`.`order_id`, "
  "`order`.`client_id`, "
  "`order`.`driver_id`, "
  "`order`.`vehicle_id`, "
  "`order`.`route_from`, "
  "`order`.`route_to`, "
  "`order`.`cargo_details`, "
  "`order`.`order_status`, "
  "`order`.`planned_departure_time`, "
  "`order`.`planned_arrival_time` "
  "FROM `order` "
  "WHERE `order`.`order_id`=?";

  const char access::object_traits_impl< ::Order, id_mysql >::update_statement[] =
  "UPDATE `order` "
  "SET "
  "`client_id`=?, "
  "`driver_id`=?, "
  "`vehicle_id`=?, "
  "`route_from`=?, "
  "`route_to`=?, "
  "`cargo_details`=?, "
  "`order_status`=?, "
  "`planned_departure_time`=?, "
  "`planned_arrival_time`=? "
  "WHERE `order_id`=?";

  const char access::object_traits_impl< ::Order, id_mysql >::erase_statement[] =
  "DELETE FROM `order` "
  "WHERE `order_id`=?";

  const char access::object_traits_impl< ::Order, id_mysql >::query_statement[] =
  "SELECT "
  "`order`.`order_id`, "
  "`order`.`client_id`, "
  "`order`.`driver_id`, "
  "`order`.`vehicle_id`, "
  "`order`.`route_from`, "
  "`order`.`route_to`, "
  "`order`.`cargo_details`, "
  "`order`.`order_status`, "
  "`order`.`planned_departure_time`, "
  "`order`.`planned_arrival_time` "
  "FROM `order`";

  const char access::object_traits_impl< ::Order, id_mysql >::erase_query_statement[] =
  "DELETE FROM `order`";

  const char access::object_traits_impl< ::Order, id_mysql >::table_name[] =
  "`order`";

  void access::object_traits_impl< ::Order, id_mysql >::
  persist (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.order_id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.order_id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Order, id_mysql >::pointer_type
  access::object_traits_impl< ::Order, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Order, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Order, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Order, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::Order, id_mysql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // triplogs_
    //
    {
      ::std::vector< ::odb::lazy_shared_ptr< ::TripLog > >& v =
        obj.triplogs_;

      triplogs_traits::load (
        v,
        esc.triplogs_);
    }

    // tripdetails_
    //
    {
      ::std::vector< ::odb::lazy_shared_ptr< ::TripDetails > >& v =
        obj.tripdetails_;

      tripdetails_traits::load (
        v,
        esc.tripdetails_);
    }
  }

  result< access::object_traits_impl< ::Order, id_mysql >::object_type >
  access::object_traits_impl< ::Order, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Order, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
