// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ORDER_ODB_HXX
#define ORDER_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "order.hxx"

#include "client-odb.hxx"
#include "driver-odb.hxx"
#include "tripdetails-odb.hxx"
#include "triplog-odb.hxx"
#include "vehicle-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Order
  //
  template <>
  struct class_traits< ::Order >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Order >
  {
    public:
    typedef ::Order object_type;
    typedef ::std::shared_ptr< ::Order > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Order
  //
  template <typename A>
  struct query_columns< ::Order, id_mysql, A >
  {
    // order_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    order_id_type_;

    static const order_id_type_ order_id;

    // client_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    client_id_type_;

    static const client_id_type_ client_id;

    // driver_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    driver_id_type_;

    static const driver_id_type_ driver_id;

    // vehicle_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    vehicle_id_type_;

    static const vehicle_id_type_ vehicle_id;

    // route_from
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    route_from_type_;

    static const route_from_type_ route_from;

    // route_to
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    route_to_type_;

    static const route_to_type_ route_to;

    // cargo_details
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    cargo_details_type_;

    static const cargo_details_type_ cargo_details;

    // order_status
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    order_status_type_;

    static const order_status_type_ order_status;

    // planned_departure_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    planned_departure_time_type_;

    static const planned_departure_time_type_ planned_departure_time;

    // planned_arrival_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    planned_arrival_time_type_;

    static const planned_arrival_time_type_ planned_arrival_time;
  };

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::order_id_type_
  query_columns< ::Order, id_mysql, A >::
  order_id (A::table_name, "`order_id`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::client_id_type_
  query_columns< ::Order, id_mysql, A >::
  client_id (A::table_name, "`client_id`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::driver_id_type_
  query_columns< ::Order, id_mysql, A >::
  driver_id (A::table_name, "`driver_id`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::vehicle_id_type_
  query_columns< ::Order, id_mysql, A >::
  vehicle_id (A::table_name, "`vehicle_id`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::route_from_type_
  query_columns< ::Order, id_mysql, A >::
  route_from (A::table_name, "`route_from`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::route_to_type_
  query_columns< ::Order, id_mysql, A >::
  route_to (A::table_name, "`route_to`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::cargo_details_type_
  query_columns< ::Order, id_mysql, A >::
  cargo_details (A::table_name, "`cargo_details`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::order_status_type_
  query_columns< ::Order, id_mysql, A >::
  order_status (A::table_name, "`order_status`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::planned_departure_time_type_
  query_columns< ::Order, id_mysql, A >::
  planned_departure_time (A::table_name, "`planned_departure_time`", 0);

  template <typename A>
  const typename query_columns< ::Order, id_mysql, A >::planned_arrival_time_type_
  query_columns< ::Order, id_mysql, A >::
  planned_arrival_time (A::table_name, "`planned_arrival_time`", 0);

  template <typename A>
  struct pointer_query_columns< ::Order, id_mysql, A >:
    query_columns< ::Order, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Order, id_mysql >:
    public access::object_traits< ::Order >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // order_id_
      //
      unsigned long long order_id_value;
      my_bool order_id_null;

      // client_id_
      //
      unsigned long long client_id_value;
      my_bool client_id_null;

      // driver_id_
      //
      unsigned long long driver_id_value;
      my_bool driver_id_null;

      // vehicle_id_
      //
      unsigned long long vehicle_id_value;
      my_bool vehicle_id_null;

      // route_from_
      //
      details::buffer route_from_value;
      unsigned long route_from_size;
      my_bool route_from_null;

      // route_to_
      //
      details::buffer route_to_value;
      unsigned long route_to_size;
      my_bool route_to_null;

      // cargo_details_
      //
      details::buffer cargo_details_value;
      unsigned long cargo_details_size;
      my_bool cargo_details_null;

      // order_status_
      //
      details::buffer order_status_value;
      unsigned long order_status_size;
      my_bool order_status_null;

      // planned_departure_time_
      //
      details::buffer planned_departure_time_value;
      unsigned long planned_departure_time_size;
      my_bool planned_departure_time_null;

      // planned_arrival_time_
      //
      details::buffer planned_arrival_time_value;
      unsigned long planned_arrival_time_size;
      my_bool planned_arrival_time_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // triplogs_
    //
    struct triplogs_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::odb::lazy_shared_ptr< ::TripLog > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef mysql::container_statements< triplogs_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        unsigned long long value_value;
        my_bool value_null;

        std::size_t version;
      };

      static void
      bind (MYSQL_BIND*,
            const MYSQL_BIND* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            my_bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    // tripdetails_
    //
    struct tripdetails_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::odb::lazy_shared_ptr< ::TripDetails > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef mysql::container_statements< tripdetails_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        unsigned long long value_value;
        my_bool value_null;

        std::size_t version;
      };

      static void
      bind (MYSQL_BIND*,
            const MYSQL_BIND* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            my_bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Order, id_common >:
    public access::object_traits_impl< ::Order, id_mysql >
  {
  };

  // Order
  //
}

#include "order-odb.ixx"

#include <odb/post.hxx>

#endif // ORDER_ODB_HXX
