/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
  `order_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `route_from` TEXT NOT NULL,
  `route_to` TEXT NOT NULL,
  `cargo_details` TEXT NOT NULL,
  `order_status` TEXT NOT NULL)
 ENGINE=InnoDB;

