// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "tripdetails-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // TripDetails
  //

  const char alias_traits<  ::Order,
    id_mysql,
    access::object_traits_impl< ::TripDetails, id_mysql >::order_tag>::
  table_name[] = "`order_id`";

  struct access::object_traits_impl< ::TripDetails, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::TripDetails, id_mysql >::id_type
  access::object_traits_impl< ::TripDetails, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::TripDetails, id_mysql >::id_type
  access::object_traits_impl< ::TripDetails, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.trip_id_value,
        i.trip_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::TripDetails, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // trip_id_
    //
    t[0UL] = 0;

    // order_
    //
    t[1UL] = 0;

    // actual_trip_status_
    //
    if (t[2UL])
    {
      i.actual_trip_status_value.capacity (i.actual_trip_status_size);
      grew = true;
    }

    // fuel_cost_
    //
    t[3UL] = 0;

    // other_expenses_
    //
    t[4UL] = 0;

    // total_cost_
    //
    t[5UL] = 0;

    // revenue_
    //
    t[6UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // trip_id_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.trip_id_value;
      b[n].is_null = &i.trip_id_null;
      n++;
    }

    // order_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.order_value;
    b[n].is_null = &i.order_null;
    n++;

    // actual_trip_status_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.actual_trip_status_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.actual_trip_status_value.capacity ());
    b[n].length = &i.actual_trip_status_size;
    b[n].is_null = &i.actual_trip_status_null;
    n++;

    // fuel_cost_
    //
    b[n].buffer_type = MYSQL_TYPE_DOUBLE;
    b[n].buffer = &i.fuel_cost_value;
    b[n].is_null = &i.fuel_cost_null;
    n++;

    // other_expenses_
    //
    b[n].buffer_type = MYSQL_TYPE_DOUBLE;
    b[n].buffer = &i.other_expenses_value;
    b[n].is_null = &i.other_expenses_null;
    n++;

    // total_cost_
    //
    b[n].buffer_type = MYSQL_TYPE_DOUBLE;
    b[n].buffer = &i.total_cost_value;
    b[n].is_null = &i.total_cost_null;
    n++;

    // revenue_
    //
    b[n].buffer_type = MYSQL_TYPE_DOUBLE;
    b[n].buffer = &i.revenue_value;
    b[n].is_null = &i.revenue_null;
    n++;
  }

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::TripDetails, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // trip_id_
    //
    if (sk == statement_insert)
    {
      long long unsigned int const& v =
        o.trip_id_;

      bool is_null (false);
      mysql::value_traits<
          long long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.trip_id_value, is_null, v);
      i.trip_id_null = is_null;
    }

    // order_
    //
    {
      ::odb::lazy_shared_ptr< ::Order > const& v =
        o.order_;

      typedef object_traits< ::Order > obj_traits;
      typedef odb::pointer_traits< ::odb::lazy_shared_ptr< ::Order > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& ptr_id (
          ptr_traits::object_id< ptr_traits::element_type  > (v));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.order_value, is_null, ptr_id);
        i.order_null = is_null;
      }
      else
        throw null_pointer ();
    }

    // actual_trip_status_
    //
    {
      ::std::string const& v =
        o.actual_trip_status_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.actual_trip_status_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.actual_trip_status_value,
        size,
        is_null,
        v);
      i.actual_trip_status_null = is_null;
      i.actual_trip_status_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.actual_trip_status_value.capacity ());
    }

    // fuel_cost_
    //
    {
      double const& v =
        o.fuel_cost_;

      bool is_null (false);
      mysql::value_traits<
          double,
          mysql::id_double >::set_image (
        i.fuel_cost_value, is_null, v);
      i.fuel_cost_null = is_null;
    }

    // other_expenses_
    //
    {
      double const& v =
        o.other_expenses_;

      bool is_null (false);
      mysql::value_traits<
          double,
          mysql::id_double >::set_image (
        i.other_expenses_value, is_null, v);
      i.other_expenses_null = is_null;
    }

    // total_cost_
    //
    {
      double const& v =
        o.total_cost_;

      bool is_null (false);
      mysql::value_traits<
          double,
          mysql::id_double >::set_image (
        i.total_cost_value, is_null, v);
      i.total_cost_null = is_null;
    }

    // revenue_
    //
    {
      double const& v =
        o.revenue_;

      bool is_null (false);
      mysql::value_traits<
          double,
          mysql::id_double >::set_image (
        i.revenue_value, is_null, v);
      i.revenue_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // trip_id_
    //
    {
      long long unsigned int& v =
        o.trip_id_;

      mysql::value_traits<
          long long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.trip_id_value,
        i.trip_id_null);
    }

    // order_
    //
    {
      ::odb::lazy_shared_ptr< ::Order >& v =
        o.order_;

      typedef object_traits< ::Order > obj_traits;
      typedef odb::pointer_traits< ::odb::lazy_shared_ptr< ::Order > > ptr_traits;

      if (i.order_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          ptr_id,
          i.order_value,
          i.order_null);

        v = ptr_traits::pointer_type (
          *static_cast<mysql::database*> (db), ptr_id);
      }
    }

    // actual_trip_status_
    //
    {
      ::std::string& v =
        o.actual_trip_status_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.actual_trip_status_value,
        i.actual_trip_status_size,
        i.actual_trip_status_null);
    }

    // fuel_cost_
    //
    {
      double& v =
        o.fuel_cost_;

      mysql::value_traits<
          double,
          mysql::id_double >::set_value (
        v,
        i.fuel_cost_value,
        i.fuel_cost_null);
    }

    // other_expenses_
    //
    {
      double& v =
        o.other_expenses_;

      mysql::value_traits<
          double,
          mysql::id_double >::set_value (
        v,
        i.other_expenses_value,
        i.other_expenses_null);
    }

    // total_cost_
    //
    {
      double& v =
        o.total_cost_;

      mysql::value_traits<
          double,
          mysql::id_double >::set_value (
        v,
        i.total_cost_value,
        i.total_cost_null);
    }

    // revenue_
    //
    {
      double& v =
        o.revenue_;

      mysql::value_traits<
          double,
          mysql::id_double >::set_value (
        v,
        i.revenue_value,
        i.revenue_null);
    }
  }

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::TripDetails, id_mysql >::persist_statement[] =
  "INSERT INTO `tripdetails` "
  "(`trip_id`, "
  "`order_id`, "
  "`actual_trip_status`, "
  "`fuel_cost`, "
  "`other_expenses`, "
  "`total_cost`, "
  "`revenue`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::TripDetails, id_mysql >::find_statement[] =
  "SELECT "
  "`tripdetails`.`trip_id`, "
  "`tripdetails`.`order_id`, "
  "`tripdetails`.`actual_trip_status`, "
  "`tripdetails`.`fuel_cost`, "
  "`tripdetails`.`other_expenses`, "
  "`tripdetails`.`total_cost`, "
  "`tripdetails`.`revenue` "
  "FROM `tripdetails` "
  "WHERE `tripdetails`.`trip_id`=?";

  const char access::object_traits_impl< ::TripDetails, id_mysql >::update_statement[] =
  "UPDATE `tripdetails` "
  "SET "
  "`order_id`=?, "
  "`actual_trip_status`=?, "
  "`fuel_cost`=?, "
  "`other_expenses`=?, "
  "`total_cost`=?, "
  "`revenue`=? "
  "WHERE `trip_id`=?";

  const char access::object_traits_impl< ::TripDetails, id_mysql >::erase_statement[] =
  "DELETE FROM `tripdetails` "
  "WHERE `trip_id`=?";

  const char access::object_traits_impl< ::TripDetails, id_mysql >::query_statement[] =
  "SELECT\n"
  "`tripdetails`.`trip_id`,\n"
  "`tripdetails`.`order_id`,\n"
  "`tripdetails`.`actual_trip_status`,\n"
  "`tripdetails`.`fuel_cost`,\n"
  "`tripdetails`.`other_expenses`,\n"
  "`tripdetails`.`total_cost`,\n"
  "`tripdetails`.`revenue`\n"
  "FROM `tripdetails`\n"
  "LEFT JOIN `order` AS `order_id` ON `order_id`.`order_id`=`tripdetails`.`order_id`";

  const char access::object_traits_impl< ::TripDetails, id_mysql >::erase_query_statement[] =
  "DELETE FROM `tripdetails`";

  const char access::object_traits_impl< ::TripDetails, id_mysql >::table_name[] =
  "`tripdetails`";

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  persist (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.trip_id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.trip_id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TripDetails, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TripDetails, id_mysql >::pointer_type
  access::object_traits_impl< ::TripDetails, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TripDetails, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TripDetails, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TripDetails, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::TripDetails, id_mysql >::object_type >
  access::object_traits_impl< ::TripDetails, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TripDetails, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
