// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TRIPLOG_ODB_HXX
#define TRIPLOG_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "triplog.hxx"

#include "client-odb.hxx"
#include "driver-odb.hxx"
#include "order-odb.hxx"
#include "tripdetails-odb.hxx"
#include "vehicle-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // TripLog
  //
  template <>
  struct class_traits< ::TripLog >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::TripLog >
  {
    public:
    typedef ::TripLog object_type;
    typedef ::std::shared_ptr< ::TripLog > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // TripLog
  //
  template <typename A>
  struct pointer_query_columns< ::TripLog, id_mysql, A >
  {
    // login_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    login_id_type_;

    static const login_id_type_ login_id;

    // trip_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    trip_id_type_;

    static const trip_id_type_ trip_id;

    // order
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    order_type_;

    static const order_type_ order;

    // actual_departure_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    actual_departure_time_type_;

    static const actual_departure_time_type_ actual_departure_time;

    // actual_arrival_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    actual_arrival_time_type_;

    static const actual_arrival_time_type_ actual_arrival_time;

    // driver_comments
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    driver_comments_type_;

    static const driver_comments_type_ driver_comments;
  };

  template <typename A>
  const typename pointer_query_columns< ::TripLog, id_mysql, A >::login_id_type_
  pointer_query_columns< ::TripLog, id_mysql, A >::
  login_id (A::table_name, "`login_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TripLog, id_mysql, A >::trip_id_type_
  pointer_query_columns< ::TripLog, id_mysql, A >::
  trip_id (A::table_name, "`trip_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TripLog, id_mysql, A >::order_type_
  pointer_query_columns< ::TripLog, id_mysql, A >::
  order (A::table_name, "`order_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TripLog, id_mysql, A >::actual_departure_time_type_
  pointer_query_columns< ::TripLog, id_mysql, A >::
  actual_departure_time (A::table_name, "`actual_departure_time`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TripLog, id_mysql, A >::actual_arrival_time_type_
  pointer_query_columns< ::TripLog, id_mysql, A >::
  actual_arrival_time (A::table_name, "`actual_arrival_time`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TripLog, id_mysql, A >::driver_comments_type_
  pointer_query_columns< ::TripLog, id_mysql, A >::
  driver_comments (A::table_name, "`driver_comments`", 0);

  template <>
  class access::object_traits_impl< ::TripLog, id_mysql >:
    public access::object_traits< ::TripLog >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // login_id_
      //
      unsigned long long login_id_value;
      my_bool login_id_null;

      // trip_id_
      //
      int trip_id_value;
      my_bool trip_id_null;

      // order_
      //
      unsigned long long order_value;
      my_bool order_null;

      // actual_departure_time_
      //
      details::buffer actual_departure_time_value;
      unsigned long actual_departure_time_size;
      my_bool actual_departure_time_null;

      // actual_arrival_time_
      //
      details::buffer actual_arrival_time_value;
      unsigned long actual_arrival_time_size;
      my_bool actual_arrival_time_null;

      // driver_comments_
      //
      details::buffer driver_comments_value;
      unsigned long driver_comments_size;
      my_bool driver_comments_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct order_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::TripLog, id_common >:
    public access::object_traits_impl< ::TripLog, id_mysql >
  {
  };

  // TripLog
  //
  template <>
  struct alias_traits<
    ::Order,
    id_mysql,
    access::object_traits_impl< ::TripLog, id_mysql >::order_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::TripLog, id_mysql >
  {
    // order
    //
    typedef
    odb::alias_traits<
      ::Order,
      id_mysql,
      access::object_traits_impl< ::TripLog, id_mysql >::order_tag>
    order_alias_;
  };

  template <typename A>
  struct query_columns< ::TripLog, id_mysql, A >:
    query_columns_base< ::TripLog, id_mysql >
  {
    // login_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    login_id_type_;

    static const login_id_type_ login_id;

    // trip_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    trip_id_type_;

    static const trip_id_type_ trip_id;

    // order
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    order_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Order,
        id_mysql,
        order_alias_ > >
    order_pointer_type_;

    struct order_type_: order_pointer_type_, order_column_type_
    {
      order_type_ (const char* t, const char* c, const char* conv)
        : order_column_type_ (t, c, conv)
      {
      }
    };

    static const order_type_ order;

    // actual_departure_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    actual_departure_time_type_;

    static const actual_departure_time_type_ actual_departure_time;

    // actual_arrival_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    actual_arrival_time_type_;

    static const actual_arrival_time_type_ actual_arrival_time;

    // driver_comments
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    driver_comments_type_;

    static const driver_comments_type_ driver_comments;
  };

  template <typename A>
  const typename query_columns< ::TripLog, id_mysql, A >::login_id_type_
  query_columns< ::TripLog, id_mysql, A >::
  login_id (A::table_name, "`login_id`", 0);

  template <typename A>
  const typename query_columns< ::TripLog, id_mysql, A >::trip_id_type_
  query_columns< ::TripLog, id_mysql, A >::
  trip_id (A::table_name, "`trip_id`", 0);

  template <typename A>
  const typename query_columns< ::TripLog, id_mysql, A >::order_type_
  query_columns< ::TripLog, id_mysql, A >::
  order (A::table_name, "`order_id`", 0);

  template <typename A>
  const typename query_columns< ::TripLog, id_mysql, A >::actual_departure_time_type_
  query_columns< ::TripLog, id_mysql, A >::
  actual_departure_time (A::table_name, "`actual_departure_time`", 0);

  template <typename A>
  const typename query_columns< ::TripLog, id_mysql, A >::actual_arrival_time_type_
  query_columns< ::TripLog, id_mysql, A >::
  actual_arrival_time (A::table_name, "`actual_arrival_time`", 0);

  template <typename A>
  const typename query_columns< ::TripLog, id_mysql, A >::driver_comments_type_
  query_columns< ::TripLog, id_mysql, A >::
  driver_comments (A::table_name, "`driver_comments`", 0);
}

#include "triplog-odb.ixx"

#include <odb/post.hxx>

#endif // TRIPLOG_ODB_HXX
