// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef VEHICLE_ODB_HXX
#define VEHICLE_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "vehicle.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Vehicle
  //
  template <>
  struct class_traits< ::Vehicle >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Vehicle >
  {
    public:
    typedef ::Vehicle object_type;
    typedef ::std::shared_ptr< ::Vehicle > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Vehicle
  //
  template <typename A>
  struct query_columns< ::Vehicle, id_mysql, A >
  {
    // vehicle_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    vehicle_id_type_;

    static const vehicle_id_type_ vehicle_id;

    // registration_number
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    registration_number_type_;

    static const registration_number_type_ registration_number;

    // vehicle_type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    vehicle_type_type_;

    static const vehicle_type_type_ vehicle_type;

    // make
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    make_type_;

    static const make_type_ make;

    // model
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    model_type_;

    static const model_type_ model;

    // technical_characteristics
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    technical_characteristics_type_;

    static const technical_characteristics_type_ technical_characteristics;

    // status
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    status_type_;

    static const status_type_ status;
  };

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::vehicle_id_type_
  query_columns< ::Vehicle, id_mysql, A >::
  vehicle_id (A::table_name, "`vehicle_id`", 0);

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::registration_number_type_
  query_columns< ::Vehicle, id_mysql, A >::
  registration_number (A::table_name, "`registration_number`", 0);

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::vehicle_type_type_
  query_columns< ::Vehicle, id_mysql, A >::
  vehicle_type (A::table_name, "`vehicle_type`", 0);

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::make_type_
  query_columns< ::Vehicle, id_mysql, A >::
  make (A::table_name, "`make`", 0);

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::model_type_
  query_columns< ::Vehicle, id_mysql, A >::
  model (A::table_name, "`model`", 0);

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::technical_characteristics_type_
  query_columns< ::Vehicle, id_mysql, A >::
  technical_characteristics (A::table_name, "`technical_characteristics`", 0);

  template <typename A>
  const typename query_columns< ::Vehicle, id_mysql, A >::status_type_
  query_columns< ::Vehicle, id_mysql, A >::
  status (A::table_name, "`status`", 0);

  template <typename A>
  struct pointer_query_columns< ::Vehicle, id_mysql, A >:
    query_columns< ::Vehicle, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Vehicle, id_mysql >:
    public access::object_traits< ::Vehicle >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // vehicle_id_
      //
      unsigned long long vehicle_id_value;
      my_bool vehicle_id_null;

      // registration_number_
      //
      details::buffer registration_number_value;
      unsigned long registration_number_size;
      my_bool registration_number_null;

      // vehicle_type_
      //
      details::buffer vehicle_type_value;
      unsigned long vehicle_type_size;
      my_bool vehicle_type_null;

      // make_
      //
      details::buffer make_value;
      unsigned long make_size;
      my_bool make_null;

      // model_
      //
      details::buffer model_value;
      unsigned long model_size;
      my_bool model_null;

      // technical_characteristics_
      //
      details::buffer technical_characteristics_value;
      unsigned long technical_characteristics_size;
      my_bool technical_characteristics_null;

      // status_
      //
      details::buffer status_value;
      unsigned long status_size;
      my_bool status_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Vehicle, id_common >:
    public access::object_traits_impl< ::Vehicle, id_mysql >
  {
  };

  // Vehicle
  //
}

#include "vehicle-odb.ixx"

#include <odb/post.hxx>

#endif // VEHICLE_ODB_HXX
