/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `vehicle`;

CREATE TABLE `vehicle` (
  `vehicle_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `registration_number` TEXT NOT NULL,
  `vehicle_type` TEXT NOT NULL,
  `make` TEXT NOT NULL,
  `model` TEXT NOT NULL,
  `technical_characteristics` TEXT NOT NULL,
  `status` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `registration_number_i`
  ON `vehicle` (`registration_number`);

